name: Intergrate-Test-Build-Deploy

on:
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.PROJECT_AUTH_ID}}
  RUN_REGION: us-east1
  JSON_KEY: ${{secrets.AUTH_JSON}}

jobs:
  I-T-B-D:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on:  ${{ matrix.platform }}

    steps:
      - name: Testing
        uses:  actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2

      - name: Test
        run:  go test ./...

      - name: Checkout
        uses: actions/checkout@v2
        with:
          version: "290.0.1"

      - name: start google cli
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.AUTH_JSON }}
      - name: set project
        run: gcloud config set project ${{ secrets.PROJECT_AUTH_ID}}
      - name: build
        run:  gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:${{secrets.TOKEN}}
      - name: deploy
        run:  gcloud run deploy $PROJECT_ID --image gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:${{secrets.TOKEN}} --platform managed --allow-unauthenticated --region $RUN_REGION